config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  root to: 'articles#index'

  devise_for :users

 devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
 end

  resources :articles do
    resources :comments
  end

  get '/users/profile' => 'profile#index'

  resources :users, only: [:index] do
    member do
      get :ban
      delete :destroy
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:User) if self.roles.blank?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def ban
    @user = User.find(params[:id])
    if @user.access_locked?
      @user.unlock_access!
    else
      @user.lock_access!
    end
    redirect_to users_path, notice: "User acces locked: #{@user.access_locked?}"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      redirect_to users_path, notice: "User deleted."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def ban_status(user)
    if user.access_locked?
      'Unban'
    else
      'Ban'
    end
  end
end

app/views/users/index.haml
%body
  /%script(src="https://unpkg.com/sweetalert/dist/sweetalert.min.js")
  - if current_user.has_role? :Admin
    .container.text-center
      %table.table
        %thead
          %tr
            %th ID
            %th Role
            %th email
            %th Sign in count
            %th Current sign in IP
            %th Current sign in at
            %th Last sign in IP
            %th Last sign in at
            %th Banned at
        %tbody
          - @users.each do |user|
            %tr
              %td
                = user.id
              %td
                = user.roles_name[0]
              %td
                = user.email
              %td
                = user.sign_in_count
              %td
                = user.last_sign_in_ip
              %td
                = user.current_sign_in_at.strftime('%d/%m/%Y %H:%M')
              %td
                = user.current_sign_in_ip
              %td= user.last_sign_in_at.strftime('%d/%m/%Y %H:%M')
              %td= user.locked_at&.strftime('%d/%m/%Y %H:%M')
              - unless current_user.id == user.id
                %td= button_to ban_status(user), ban_user_path(user), method: :get, data: { turbo_confirm: "sure?" }, class: "btn btn-danger btn-sm"
                %td= button_to 'Remove', user_path(user), method: :delete, data: { turbo_confirm: "sure?" }, class: "btn btn-danger btn-sm"

/ = link_to 'uyari', '#', onclick: 'sure()'
/ :javascript
/   function sure()
/   {
/     swal({
/       title: "Are you sure?",
/       text: "Once deleted, you will not be able to recover this imaginary file!",
/       icon: "warning",
/       buttons: true,
/       dangerMode: true
/       })
/     .then((willDelete) => {
/       if (willDelete) {
/         swal("Poof! Your imaginary file has been deleted!", { icon: "success" });
/       }
/       swal("Your imaginary file is safe!", { icon: "success" });
/       })
/   };